### ISSUE TITLE
Remove `disable-auto-fix` options

### ISSUE THREAD

**Issue by hudochenkov** [yuschick/stylelint-plugin-logical-css#18]
Stylelint has a standard way of [disabling autofix for a single rule](https://stylelint.io/user-guide/configure#disablefix): `disableFix` option. Then in a rule code you can get a value from [`context.fix`](https://stylelint.io/developer-guide/rules#add-autofix).

Consider removing own option to keep plugin aligned to Stylelint conventions.

**Comment by yuschick** [comment]
Oh, good call. I didn't know this. I will take a look at removing the option.

**Comment by yuschick** [comment]
This issue has been addressed and released in v0.13.0. The `disable-auto-fix` option is no longer available, and Stylelint's `disableFix` option should be used instead.
