### ISSUE TITLE
add support to stylelint 16

### ISSUE THREAD

**Issue by ghost** [yuschick/stylelint-plugin-logical-css#22]
Please support stylelint 16.0.0, the big one

Now the code is in ESM instead of CommonJS 

Very good

Stylelint team published docs to know how to migrate with ease.

No need to keep support to commons from now on.

Style lint 16 is not allowed in your package.json. remove this restriction to

**Comment by yuschick** [comment]
Stylelint 16 will be supported shortly, as it has now been supported in the Defensive CSS plugin and those changes will be carried over to here.

https://github.com/yuschick/stylelint-plugin-defensive-css/pull/28

**Comment by yuschick** [comment]
Version 1.0.0 was published with support for Stylelint 16. Thank you for reporting 🚀
